# Generated by Django 3.2 on 2021-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=30, verbose_name='آیدی کاربر')),
                ('Name', models.CharField(max_length=100, verbose_name='اسم جایزه')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جایزه ها',
            },
        ),
        migrations.CreateModel(
            name='LuckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='اسم')),
                ('Number', models.IntegerField(default=0, verbose_name='تعداد')),
                ('Degree', models.IntegerField(default=0, verbose_name='درجه(تخصصی)')),
            ],
            options={
                'verbose_name': 'تنظیمات جایزه',
                'verbose_name_plural': 'تنظیمات جایزه ها',
            },
        ),
    ]
