# Generated by Django 3.2.3 on 2021-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luck',
            name='Paied',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
    ]
