# Generated by Django 3.2 on 2021-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditPack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpack',
            name='Time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ اعمال'),
        ),
    ]
