# Generated by Django 3.2.3 on 2021-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditPack', '0002_alter_creditpack_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpack',
            name='ChatIDBuyer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
