# Generated by Django 3.2.3 on 2021-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditPack', '0003_creditpack_chatidbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpack',
            name='BuyerMessageID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='ChatIDSeller',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='SellerMessageID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
