# Generated by Django 3.2.3 on 2021-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditPack', '0004_auto_20210624_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpacksitesetting',
            name='FeePercent',
            field=models.IntegerField(null=True, verbose_name='درصد کارمزد'),
        ),
    ]
