# Generated by Django 3.2.3 on 2021-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditPack', '0005_creditpacksitesetting_feepercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpacksitesetting',
            name='FeePercent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='درصد کارمزد'),
        ),
    ]
