# Generated by Django 3.2 on 2021-05-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bot', '0002_telegramuser_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableMoney', models.IntegerField(default=0, verbose_name='پول موجود')),
                ('BlockedMoney', models.IntegerField(default=0, verbose_name='پول بلوکه شده')),
                ('ToTelegramUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bot.telegramuser', verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Before', models.IntegerField(verbose_name='موجودی قبل از تراکنش')),
                ('Value', models.IntegerField(verbose_name='ارزش ترکانش')),
                ('Fee', models.IntegerField(verbose_name='کارمزد تراکنش')),
                ('Next', models.IntegerField(verbose_name='موجودی بعد از تراکنش')),
                ('Cause', models.CharField(max_length=200, verbose_name='توضیحات تراکنش')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('ToWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WalletTransition.wallet', verbose_name='کیف پول مربوطه')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
