# Generated by Django 3.2 on 2021-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletTransition', '0002_transition_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='Done',
            field=models.BooleanField(default=False, verbose_name='تراکنش انجام شده'),
        ),
    ]
