# Generated by Django 3.2.3 on 2021-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletTransition', '0003_alter_transition_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='TranTime',
            field=models.DateField(auto_now=True, null=True, verbose_name='تاریخ تراکنش'),
        ),
    ]
