# Generated by Django 3.2 on 2021-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='نام پارامتر')),
                ('Value', models.IntegerField(verbose_name='مقدار پارامتر')),
                ('PersianName', models.CharField(max_length=100, verbose_name='نام فارسی پارامتر')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
