# Generated by Django 3.2.3 on 2021-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='Value',
            field=models.DecimalField(decimal_places=1, max_digits=20, verbose_name='مقدار پارامتر'),
        ),
    ]
