# Generated by Django 3.2 on 2021-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_auto_20210503_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='BuyID',
            field=models.CharField(default=0, max_length=20, verbose_name='آیدی خریدار'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='SellID',
            field=models.CharField(default=0, max_length=20, verbose_name='آیدی فروشنده'),
        ),
    ]
