# Generated by Django 3.2 on 2021-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0003_auto_20210503_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loansitesetting',
            options={'verbose_name': 'تنظیم وام', 'verbose_name_plural': 'تنظیمات وام ها'},
        ),
        migrations.AlterField(
            model_name='loansitesetting',
            name='Duration',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='loansitesetting',
            name='Price',
            field=models.IntegerField(verbose_name='قیمت در سایت'),
        ),
        migrations.AlterField(
            model_name='loansitesetting',
            name='Value',
            field=models.IntegerField(verbose_name='ارزش'),
        ),
    ]
