# Generated by Django 3.2 on 2021-05-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0005_auto_20210504_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Done',
            new_name='Conf',
        ),
        migrations.AddField(
            model_name='loan',
            name='BuyConf',
            field=models.BooleanField(default=False, verbose_name='تاییده خریدار'),
        ),
        migrations.AddField(
            model_name='loan',
            name='SellConf',
            field=models.BooleanField(default=False, verbose_name='تاییده ی فروشنده'),
        ),
    ]
