# Generated by Django 3.2 on 2021-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0006_auto_20210504_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='BuyID',
            field=models.CharField(default='0', max_length=20, verbose_name='آیدی خریدار'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='SellID',
            field=models.CharField(default='0', max_length=20, verbose_name='آیدی فروشنده'),
        ),
    ]
