# Generated by Django 3.2 on 2021-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0007_auto_20210504_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ChatID',
            field=models.CharField(default=0, max_length=20, verbose_name='چتی که درخواست ثبت کرده'),
            preserve_default=False,
        ),
    ]
