# Generated by Django 3.2 on 2021-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0008_loan_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Time',
            field=models.CharField(max_length=10, null=True, verbose_name='تاریخ اعمال'),
        ),
    ]
