# Generated by Django 3.2.3 on 2021-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0009_alter_loan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ChatIDBuyer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
