# Generated by Django 3.2.3 on 2021-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0010_loan_chatidbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='BuyerMessageID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='SellerMessageID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
