# Generated by Django 3.2.3 on 2021-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0011_auto_20210623_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ChatIDSeller',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
