# Generated by Django 3.2.3 on 2021-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0012_loan_chatidseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansitesetting',
            name='FeePercent',
            field=models.IntegerField(null=True, verbose_name='درصد کارمزد'),
        ),
    ]
