# Generated by Django 3.2 on 2021-05-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('ClubCode', models.CharField(max_length=6, verbose_name='کد باشگاه آگاه')),
                ('PhoneNumber', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('BankName', models.CharField(max_length=50, null=True, verbose_name='نام بانک')),
                ('BankAccount', models.CharField(max_length=100, null=True, verbose_name='شماره حساب بانکی')),
                ('Shaba', models.CharField(max_length=26, null=True, verbose_name='شماره شبا')),
                ('ToTelegramUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bot.telegramuser', verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
