# Generated by Django 3.2.3 on 2021-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_userconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UserConf',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
