# Generated by Django 3.2 on 2021-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('ClubCode', models.CharField(max_length=6, verbose_name='کد باشگاه')),
                ('Number', models.IntegerField(verbose_name='تعداد امتیازها')),
                ('Price', models.IntegerField(verbose_name='قیمت(ریال)')),
                ('SellID', models.CharField(default='0', max_length=20, verbose_name='آیدی فروشنده')),
                ('SellTransition', models.IntegerField(null=True, verbose_name='تراکنش مربوط به فروش')),
                ('BuyID', models.CharField(default='0', max_length=20, verbose_name='آیدی خریدار')),
                ('BuyTransition', models.IntegerField(null=True, verbose_name='تراکنش مربوط به خرید')),
                ('SellConf', models.BooleanField(default=False, verbose_name='تاییده ی فروشنده')),
                ('BuyConf', models.BooleanField(default=False, verbose_name='تاییده ی خریدار')),
                ('Conf', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('ChatID', models.CharField(max_length=20, verbose_name='چتی که درخواست ثبت کرده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
            },
        ),
    ]
