# Generated by Django 3.2 on 2021-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='Penalty',
            field=models.IntegerField(default=0, verbose_name='جریمه ها'),
        ),
    ]
